// ignore_for_file: constant_identifier_names
const USER_DATA = 'USER_DATA';
const USER_SESSION_TOKEN = 'USER_SESSION_TOKEN';
const USER_REFRESH_TOKEN = 'USER_REFRESH_TOKEN';
const USER_REMEMBER_ME_EMAIL = 'USER_REMEMBER_ME_EMAIL';
const USER_REMEMBER_ME_PASS = 'USER_REMEMBER_ME_PASS';
const USER_REMEMBER_ME_ENABLED = 'USER_REMEMBER_ME_ENABLED';
const USER_BIOMETRIC_ENABLED = 'USER_BIOMETRIC_ENABLED';
const HIDE_AUTH_ONBOARDING_SCREEN = 'HIDE_AUTH_ONBOARDING_SCREEN';
const USER_DEVICE_TOKEN = 'USER_DEVICE_TOKEN';
