name: swappr
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'


#-------------- PACKAGES----------------#
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.4.0
  intl_phone_field: ^3.2.0
  flutter_slidable: ^3.1.0
  loader_overlay: ^2.2.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.0
  local_auth: ^2.2.0
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  timeline_tile: ^2.0.0
  timelines: ^0.1.0


  get: ^4.6.6
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  flutter_svg: ^2.0.10+1



  #------------------- ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  #------------- LOCAL ASSETS --------------------#
  assets:
    - .env
    - assets/logos/
    - assets/icons/bottomNavIcons/
    - assets/icons/profileIcons/
    - assets/icons/countryIcons/
    - assets/icons/homeIcons/
    - assets/icons/verifyIcons/
    - assets/images/

  #-------------- LOCAL FONTS --------------------#
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900