// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzZapdz0t96_Fm1vhhzF7fe6tiXfd0TAE',
    appId: '1:288340283210:android:a367548037de94eb0cbbb3',
    messagingSenderId: '288340283210',
    projectId: 'pouch-e9c6e',
    storageBucket: 'pouch-e9c6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYFFmNnwXKOG8pEpvmWSWtViABWKz0ez0',
    appId: '1:288340283210:ios:5097ebb1e126f6610cbbb3',
    messagingSenderId: '288340283210',
    projectId: 'pouch-e9c6e',
    storageBucket: 'pouch-e9c6e.appspot.com',
    iosBundleId: 'com.example.pouch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYFFmNnwXKOG8pEpvmWSWtViABWKz0ez0',
    appId: '1:288340283210:ios:5097ebb1e126f6610cbbb3',
    messagingSenderId: '288340283210',
    projectId: 'pouch-e9c6e',
    storageBucket: 'pouch-e9c6e.appspot.com',
    iosBundleId: 'com.example.pouch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDISP5_wpo_voLB0VcLPuQuRiIWJdPoQq0',
    appId: '1:288340283210:web:90baa616662874360cbbb3',
    messagingSenderId: '288340283210',
    projectId: 'pouch-e9c6e',
    authDomain: 'pouch-e9c6e.firebaseapp.com',
    storageBucket: 'pouch-e9c6e.appspot.com',
  );
}
